### ISSUE TITLE
[Linux] getValue() trace on TextCtrl traces something completely different

### ISSUE THREAD

**Issue by tienery** [ianharrigan/hxWidgets#25] opened 2016-04-30 15:54 UTC
I went ahead to implement the `getValue()` and `setValue()` methods in the `TextCtrl` as without them the control is kind of useless on its own. But testing it, I'm getting unusual results on Linux, and I was wondering if you can reproduce these results and find out what's causing it.

Using the following code:

        var app = new App();
        app.init();
        
        var mainFrame = new Frame(null, "Test");
        mainFrame.setSize(800, 600);
        mainFrame.show(true);
        
        var mainPanel = new Panel(mainFrame);
        mainPanel.setSize(800, 600);
        
        var mainTextBox = new TextCtrl(mainPanel, TextCtrlStyle.MULTILINE);
        mainTextBox.move(3, 3);
        //mainTextBox.setSize(750, 140);
        mainTextBox.setClientSize(750, 300);
        mainTextBox.bind(EventType.TEXT, function(e)
        {
            trace(mainTextBox.getValue());
        });

I get the following trace output:

![img](http://i.imgur.com/VPZL6nU.png)

**Comment by ianharrigan** [comment] 2016-04-30 16:03
what happens if you set the value first?

**Comment by tienery** [comment] 2016-04-30 16:05
Setting it using an additional line of code: `mainTextBox.setValue("");` doesn't seem to make much difference.

**Comment by ianharrigan** [comment] 2016-04-30 16:05
btw... there is already a `value` prop

**Comment by ianharrigan** [comment] 2016-04-30 16:05
actually, thats not true... ignore me...

**Comment by tienery** [comment] 2016-04-30 16:06
I will try to use the `label` field see if that makes any difference.

**Comment by ibilon** [comment] 2016-04-30 16:11
`getValue` returns a `wxString` not a `std::string` that could be the cause of the problem.

**Comment by ianharrigan** [comment] 2016-04-30 16:13
i just implemented `.value` as:

```haxe
@:native("SetValue")            public function setValue(value:ConstCharStar):Void;
@:native("GetValue")            public function getValue():ConstCharStar;
```

and tried:
```haxe
var textctrl:TextCtrl = new TextCtrl(frame, null, TextCtrlStyle.MULTILINE | TextCtrlStyle.RICH);
textctrl.appendText("This is line 1\n");
textctrl.appendText("This is line 2\n");
textctrl.appendText("This is line 3\n");
textctrl.appendText("This is line 4\n");
textctrl.appendText("This is line 5\n");
trace("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX " + textctrl.value);
```

And it seemed to work fine... ie, trace was correct

**Comment by tienery** [comment] 2016-04-30 16:18
Have you tried it with the event binding? That's where it goes wrong for me.

**Comment by ianharrigan** [comment] 2016-04-30 16:20
![image](https://cloud.githubusercontent.com/assets/3024242/14937202/3472fb66-0f00-11e6-9b9b-dd559d38025d.png)

This is windows though

**Comment by tienery** [comment] 2016-04-30 16:22
Yeah, on Linux I'm having different results with your code as well... I'm getting this:

![img](http://i.imgur.com/dy1Ct5L.png)

**Comment by ianharrigan** [comment] 2016-04-30 16:25
this is kinda strange though:

```
            var label:StaticText = new StaticText(box, "Static text");
            label.label = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.";
            trace(">>>>>>>>>> " + label.label);
```

![image](https://cloud.githubusercontent.com/assets/3024242/14937219/dac97e7c-0f00-11e6-9bbf-1cb4922fa048.png)

**Comment by tienery** [comment] 2016-04-30 16:25
Is that on Linux?

**Comment by ianharrigan** [comment] 2016-04-30 16:26
nope

**Comment by ianharrigan** [comment] 2016-05-01 16:07
So this will be fixed soon(ish). Im currently reworking the externs with @ibilon to make the externs (and the wrappers) better, and part of that is to use wxStrings properly when appropriate. Theres a lot to get through but it'll get done eventually - you can follow progress here: https://github.com/ianharrigan/hxWidgets/tree/feature/haxe-3.3

**Comment by ianharrigan** [comment] 2016-05-06 07:50
Can you try that now from `master` - the branch has now been merged and the externs correctly use `wxString` which seems to overcome any issues i had with large strings, im guessing it will have a similar effect to you.

**Comment by tienery** [comment] 2016-05-06 12:33
Okay, I'll try it later when I get the chance.

**Comment by mrcdk** [comment] 2016-05-21 18:11
This seems to be fixed
![http://i.imgur.com/fDfwp3N.png](http://i.imgur.com/fDfwp3N.png)

Ubuntu 16.04 using latest master and dev Haxe and hxcpp

**Comment by ianharrigan** [comment] 2016-05-21 18:14
Cool, yeah, pretty sure all the string issues are fixed now since we are using wxString. Ill close this and if any more issues pop up we can deal with them as and when. 

Cheers.

**Closed by ianharrigan** 2016-05-21 18:14 UTC
